default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: db_guy
  password: db_pass


development:
  <<: *default
  database: flashcards_development

test:
  <<: *default
  database: flashcards_test

production:
  <<: *default
  database: flashcards_production
